core/App/constants.ts
core/App/contexts/configuration.tsx
core/App/defaultConfiguration.ts
core/App/types/proof-reqeust-template.ts
core/App/utils/proof-request.ts
core/App/utils/proof.ts
core/__tests__/utils/__snapshots__/proof-request.test.ts.snap
core/__tests__/utils/__snapshots__/proof.test.ts.snap
core/__tests__/utils/proof-request.test.ts
core/__tests__/utils/proof.test.ts

Added default templates and helpers functions for indy requests and proofs
[BCGOVSSIMO-1](https://jira.dsr-corporation.com/browse/BCGOVSSIMO-1)
[BCGOVSSIMO-21](https://jira.dsr-corporation.com/browse/BCGOVSSIMO-21)
Pro Tip 🤓
_PR …

Added default templates and helpers functions for indy requests and proofs

---

core/App/contexts/reducers/store.ts
core/App/contexts/store.tsx
core/App/localization/en/index.ts
core/App/localization/fr/index.ts
core/App/localization/pt-br/index.ts
core/App/navigators/ProofRequestStack.tsx
core/App/navigators/RootStack.tsx
core/App/screens/Developer.tsx
core/App/screens/ListProofRequests.tsx
core/App/screens/Settings.tsx
core/App/types/navigators.ts
core/App/types/state.ts

Added Send Proof Request option into the setting screen. 
By default the option is hidden and need to be enable in the developer mode.
https://jira.dsr-corporation.com/browse/BCGOVSSIMO-2
Pro Tip 🤓
_PR template adapted from the …

Added Send Proof Request option into setting screen

---

core/App/screens/Scan.tsx
core/App/utils/helpers.ts

Updated scanner to accept raw JSON message, so that we can put Proof Request message directly into QR code.
https://jira.dsr-corporation.com/browse/BCGOVSSIMO-17
Pro Tip 🤓

Updated scanner to accept raw JSON message

---

core/App/components/misc/QRRenderer.tsx
core/App/constants.ts
core/App/localization/en/index.ts
core/App/localization/fr/index.ts
core/App/localization/pt-br/index.ts
core/App/navigators/ProofRequestStack.tsx
core/App/screens/ProofDetails.tsx
core/App/screens/ProofRequesting.tsx
core/App/types/navigators.ts
core/App/types/proof-reqeust-template.ts
core/App/utils/proof-request.ts
core/App/utils/proof.ts
core/__tests__/utils/__snapshots__/proof-request.test.ts.snap
core/__tests__/utils/__snapshots__/proof.test.ts.snap
core/__tests__/utils/proof-request.test.ts
core/__tests__/utils/proof.test.ts

Implemented logic around the proof generation and waiting result
https://jira.dsr-corporation.com/browse/BCGOVSSIMO-6
Pro Tip 🤓

Implemented logic around proof generation and waiting result

---

core/App/components/chat/ChatActions.tsx
core/App/localization/en/index.ts
core/App/localization/fr/index.ts
core/App/localization/pt-br/index.ts
core/App/screens/Chat.tsx
core/App/screens/ListProofRequests.tsx
core/App/theme.ts
core/App/types/navigators.ts

Updated chat screen to add an actions button with the option to send a proof request.
https://jira.dsr-corporation.com/browse/BCGOVSSIMO-9
Pro Tip 🤓

Added actions button to chat screen

---

core/App/localization/en/index.ts
core/App/localization/fr/index.ts
core/App/localization/pt-br/index.ts
core/App/screens/ListProofRequests.tsx
core/App/screens/ProofRequestDetails.tsx
core/App/types/navigators.ts

Fixed error with sending a Proof Request to a specific contact. The connection id was passing incorrectly.
Pro Tip 🤓

Fixed error with sending a Proof Request to specific contact

---

core/App/components/chat/ChatActions.tsx
core/App/components/misc/SharedProofData.tsx
core/App/localization/en/index.ts
core/App/localization/fr/index.ts
core/App/localization/pt-br/index.ts
core/App/navigators/ProofRequestStack.tsx
core/App/screens/ListProofRequests.tsx
core/App/screens/ProofDetails.tsx
core/App/screens/ProofRequestDetails.tsx
core/App/screens/ProofRequesting.tsx

Made views scrollable and corrected layout.
Pro Tip 🤓

Made views scrollable and corrected layout

---

core/App/screens/ListProofRequests.tsx

Reverted navigation changes
Pro Tip 🤓

Reverted navigation changes

---

core/App/components/misc/SharedProofData.tsx
core/App/screens/ListProofRequests.tsx
core/App/screens/ProofDetails.tsx
core/App/screens/ProofRequestDetails.tsx
core/App/screens/ProofRequesting.tsx
core/App/types/record.ts
core/App/utils/oca.ts
core/__mocks__/custom/@react-navigation/native.ts
core/__tests__/contexts/configuration.ts
core/__tests__/screens/ListProofRequests.test.tsx
core/__tests__/screens/ProofRequestDetails.test.tsx
core/__tests__/screens/__snapshots__/ListProofRequests.test.tsx.snap
core/__tests__/screens/__snapshots__/ProofRequestDetails.test.tsx.snap
core/verifier/__tests__/verifier/__snapshots__/proof.test.ts.snap
core/verifier/__tests__/verifier/proof-request.test.ts
core/verifier/__tests__/verifier/proof.test.ts
core/verifier/constants.ts
core/verifier/hooks/proofs.ts
core/verifier/types/proof.ts
core/verifier/utils/proof-request.ts
core/verifier/utils/proof.ts

Added tests for the list of proof request templates and template details screens.
Pro Tip 🤓

test: Added tests for list of proof request templates

---

core/App/localization/en/index.ts
core/App/localization/fr/index.ts
core/App/localization/pt-br/index.ts
core/App/screens/Chat.tsx
core/App/screens/CommonDecline.tsx
core/App/screens/ProofDetails.tsx
core/App/screens/ProofRequestUsageHistory.tsx
core/App/screens/ProofRequesting.tsx
core/verifier/utils/proof.ts

Added support for declined requests.
Pro Tip 🤓

Added support for declined requests

---

core/App/components/listItems/ContactListItem.tsx
core/App/components/misc/EmptyList.tsx
core/App/screens/ListContacts.tsx

Update UI for the contact list item
https://jira.dsr-corporation.com/browse/BCGOVSSIMO-35
Pro Tip 🤓

BCGOVSSIMO-35 Connections List redesign

---

core/App/localization/en/index.ts
core/App/localization/fr/index.ts
core/App/localization/pt-br/index.ts
core/App/navigators/ProofRequestStack.tsx

Added title to the request usage history screen and corrected back redirection.
Pro Tip 🤓

Added title to the request usage history screen and corrected back redirection

---

core/App/constants.ts
core/App/contexts/reducers/store.ts
core/App/contexts/store.tsx
core/App/hooks/connections.ts
core/App/localization/en/index.ts
core/App/localization/fr/index.ts
core/App/localization/pt-br/index.ts
core/App/navigators/ContactStack.tsx
core/App/screens/ConnectionInvitation.tsx
core/App/screens/Developer.tsx
core/App/screens/Settings.tsx
core/App/types/navigators.ts
core/App/types/state.ts
core/App/utils/helpers.ts

Added ability to create connection invitations. 
User can enable this featured in the developer mode. After enabling new setting will be added.
https://jira.dsr-corporation.com/browse/BCGOVSSIMO-40
Pro Tip 🤓
_PR template adapted …

feat: [BCGOVSSIMO-40] Added ability to create connection invitations

---

core/verifier/__tests__/verifier/__snapshots__/proof-request.test.ts.snap
core/verifier/types/proof-reqeust-template.ts
core/verifier/utils/proof-request.ts

Corrected setting of proof request restrictions.
Pro Tip 🤓

fix: Set request restrictions properly

---

core/App/components/misc/SharedProofData.tsx
core/App/screens/ProofDetails.tsx
core/App/screens/ProofDetailsHistory.tsx

Add scroll view for Proof Details and Proof Details History screens
https://jira.dsr-corporation.com/browse/BCGOVSSIMO-47
Pro Tip 🤓

BCGOVSSIMO-47 [Proof Details] Сredential list is not scrolled

---

core/App/screens/ProofRequestUsageHistory.tsx

Change text color
https://jira.dsr-corporation.com/browse/BCGOVSSIMO-44
Pro Tip 🤓

BCGOVSSIMO-44 [Template History] Field names are not displayed in history card

---

core/App/screens/ProofDetails.tsx

Add connection label text
https://jira.dsr-corporation.com/browse/BCGOVSSIMO-46
Pro Tip 🤓

BCGOVSSIMO-46 [Proof Details] Text of the header does not indicate from whom information was received

---

core/App/components/misc/SharedProofData.tsx

Replace this text with a high-level summary of the changes included in this PR.
Please reference here any issue #'s that are relevant to this PR, or simply enter "N/A" if this PR does not relate to any existing issues.
Pro Tip 🤓
_PR …

Fixed A FlatList nested in a ScrollView

---

core/App/screens/ProofDetails.tsx

Corrected phrase template usage
Pro Tip 🤓

Corrected phrase template usage

---

core/App/screens/ProofDetails.tsx
core/App/screens/ProofRequesting.tsx

Added back button handler for ProofDetails and ProofRequesting views.
https://jira.dsr-corporation.com/browse/BCGOVSSIMO-45
Pro Tip 🤓

Added back button handler for ProofDetails and ProofRequesting views

---

core/App/localization/en/index.ts
core/App/localization/fr/index.ts
core/App/localization/pt-br/index.ts

Made the header title shorter.
Pro Tip 🤓

Made the header title for Proof Request Usage History screen shorter

---

core/App/screens/Developer.tsx

Replace this text with a high-level summary of the changes included in this PR.
Please reference here any issue #'s that are relevant to this PR, or simply enter "N/A" if this PR does not relate to any existing issues.
Pro Tip 🤓
_PR …

Use flex for Text on the Developer screen to avoid overflow

---

core/App/screens/ProofRequest.tsx
core/App/utils/helpers.ts

Merge requested attributes and predicates correctly.
Pro Tip 🤓

Merge requested attributes and predicates correctly

---

core/__tests__/screens/__snapshots__/ProofDetails.test.tsx.snap

Replace this text with a high-level summary of the changes included in this PR.
Please reference here any issue #'s that are relevant to this PR, or simply enter "N/A" if this PR does not relate to any existing issues.
Pro Tip 🤓
_PR …

Updated ProofDetails screen snapshot after text changes
